<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>


    <xacro:property name="chassis_radius" value="0.175"/> <!-- R = 175mm-->
    <xacro:property name="chassis_height" value="0.005"/> <!-- h = 5mm-->
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="wheel_radius" value="0.0325"/> <!-- R = 32.5mm-->
    <xacro:property name="wheel_thickness" value="0.025"/> <!-- h = 25mm-->
    <xacro:property name="wheel_mass" value="0.05"/>
    <xacro:property name="wheel_offset_x" value="0.175"/> <!-- x = 175mm-->
    <xacro:property name="wheel_offset_y" value="0.1425"/> <!-- y = 142.5mm-->
    <xacro:property name="wheel_offset_z" value="0.0125"/> <!-- z = 12.5mm-->
    <xacro:property name="caster_wheel_radius" value="0.01"/>  <!-- R = 10mm-->
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.32"/> <!-- x = 145 + 175mm-->
    <xacro:property name="caster_wheel_offset_z" value="-0.01"/> <!-- z = 10mm-->

    <material name="white">
        <color rgba="1 1 1 1" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">
      <visual>
        <origin xyz="0 0 0.015" rpy="0 0 0" />
      </visual>
    </link>

    <!-- CHASSIS LINK -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="-${wheel_offset_x} 0 0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${chassis_radius} 0 -${chassis_height/2}"/>
            <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <visual>
            <origin xyz="${chassis_radius} 0 0.1275"/>
            <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_height}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <!-- Tru 1 -->
        <visual>
            <origin xyz="0.035 0.05799 0.0625"/>
            <geometry>
                <cylinder radius="0.008" length="0.125"/>
            </geometry>
            <material name="black"/>
        </visual> 
        <!-- Tru 2 -->
        <visual>
            <origin xyz="0.035 -0.05799 0.0625"/>
            <geometry>
                <cylinder radius="0.008" length="0.125"/>
            </geometry>
            <material name="black"/>
        </visual>
        <!-- Tru 3 -->
        <visual>
            <origin xyz="0.315 0.05799 0.0625"/>
            <geometry>
                <cylinder radius="0.008" length="0.125"/>
            </geometry>
            <material name="black"/>
        </visual>
        <!-- Tru 4 -->
        <visual>
            <origin xyz="0.315 -0.05799 0.0625"/>
            <geometry>
                <cylinder radius="0.008" length="0.125"/>
            </geometry>
            <material name="black"/>
        </visual>

        <collision>
            <origin xyz="${chassis_radius} 0 -${chassis_height/2}"/>
            <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_height}"/>
            </geometry>
        </collision>
        <collision>
            <origin xyz="${chassis_radius} 0 0.1275"/>
            <geometry>
                <cylinder radius="${chassis_radius}" length="${chassis_height}"/>
            </geometry>
        </collision>

        <xacro:inertial_cylinder mass="${chassis_mass}" length="${chassis_height}" radius="${chassis_radius}">
            <origin xyz="${chassis_radius} 0 -${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
         <xacro:inertial_cylinder mass="${chassis_mass}" length="${chassis_height}" radius="${chassis_radius}">
            <origin xyz="${chassis_radius} 0 0.1275" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- LEFT WHEEL LINK -->

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${wheel_offset_y} ${wheel_offset_z}" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link> 

    <!-- RIGHT WHEEL LINK -->

   <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 -${wheel_offset_y} ${wheel_offset_z}" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- CASTER WHEEL LINK -->

    <joint name="caster_before_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_before_wheel"/>
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
    </joint>

    <link name="caster_before_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <joint name="caster_after_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_after_wheel"/>
        <origin xyz="0.03 0 ${caster_wheel_offset_z}"/>
    </joint>

    <link name="caster_after_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

</robot>
